version: '3.8'

services:
  acolher-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acolher-app
    ports:
      - "90:90"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - acolher_default  # Adiciona à rede correta

networks:
  acolher_default:
    external: true  # Usa a rede já existente
